config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  resources :posts do
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
      get 'tag_search'
    end
  end
  resources :users, only: [:show, :edit, :update] do
    get :likes, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post, dependent: :destroy

  validates :comment, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :user, optional: true
  has_many :post_tags
  has_many :tags, through: :post_tags
  has_many :likes
  has_many :comments

  with_options presence: true do
    validates :name
    validates :text
    validates :image
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags
  has_many :posts, through: :post_tags

  validates :tagname, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :comments
  
  validates :nickname, presence: true
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX

  def liked_by?(post_id)
    likes.where(post_id: post_id).exists?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/posts/#{comment.post.id}"
  end

  private

  def comment_params
    params.require(:comment).permit(:comment).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :post_params

  def create
    Like.create(user_id: current_user.id, post_id: params[:id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, post_id: params[:id])
    like.destroy
  end

  private

  def post_params
    @post = Post.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :move_to_root_path, only: [:show, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :update, :edit, :destroy]

  def index
    @posts = Post.all.order(created_at: :desc)
    if params[:search].present?
      posts = Post.posts_serach(params[:search])
    elsif params[:tag_id].present?
      @tag = Tag.find(params[:tag_id])
      post = @tag.posts.order(created_at: :desc)
    end
    @tag_lists = Tag.all
  end

  def new
    @post = PostsTag.new
  end
  
  def create
    @post = PostsTag.new(post_params)
    if @post.valid?
      @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def search
    redirect_to root_path if params[:keyword] == ""
    split_keyword = params[:keyword].to_s.split(/[[:blank:]]+/)
    @tags = []
    split_keyword.each do |keyword|
      next if keyword == ""
      @tags += Tag.order(created_at: :desc).where(['tagname LIKE ?', "%#{params[:keyword]}%"] )
      end
    @tags.uniq!
  end

  def tag_search
    return nil if params[:keyword] == ""
    tag = Tag.where(['tagname LIKE ?', "%#{params[:keyword]}%"] )
    render json:{ keyword: tag }
  end

  private

  def post_params
    params.require(:posts_tag).permit(:text, :name, :image, :tagname).merge(user_id: current_user.id)
  end

  def move_to_root_path
    @post = Post.find(params[:id])
    unless user_signed_in? && current_user.id == @post.user.id
      redirect_to root_path
    end
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def save_posts(tags)
    current_tags = seif.tags.pluk(:tag_name) unless self.tags.nill?
    old_tags = current_tags - tags
    new_tags = tags - current_tags

    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(tag_name: old_name)
    end

    new_tags.each do |new_name|
      post_tag = Tag.find_or_create_by(tag_name: new_name)
      self.tags << post_tag
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @posts = user.posts.order(created_at: :desc)
    @nickname = current_user.nickname
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def likes
    likes = Like.where(user_id: current_user.id).pluck(:post_id)
    @like_list = Post.find(likes)
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NShare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <h1 class="grid-6"><a href="/">N-share</a></h1>
      <div class="user_nav-grid-6">
      <% if user_signed_in? %>
        <%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname" %>
        <%= link_to 'ログアウト', destroy_user_session_path(params[:id]), method: :delete, class: "logout" %>
        <%= link_to '投稿する', new_post_path, class:"create-post" %>
      <% else %>
        <%= link_to 'Log In', new_user_session_path, class: "login" %>
        <%= link_to 'Sign Up', new_user_registration_path, class: "sign-up" %>
      <% end %>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/likes/create.js.erb
document.getElementById('post_<%= @post.id %>').innerHTML = '<%= j(render @post) %>'

app/views/likes/destroy.js.erb
document.getElementById('post_<%= @post.id %>').innerHTML = '<%= j(render @post) %>'

app/views/posts/_post.html.erb
<% if user_signed_in? %>
  <% if current_user.liked_by?(post.id) %>
    <div>
      <%= link_to destroy_like_path(post.id), class:"like-link", method: :delete, remote: true do %>
        <i class="fa fa-heart unlike-btn"></i>
      <% end %>
      <%= post.likes.count %>
    </div>
  <% else %>
    <div>
      <%= link_to create_like_path(post.id), class:"like-link", method: :post, remote: true do %>
        <i class="fa fa-heart to-unlike-btn"></i>
      <% end %>
      <%= post.likes.count %>
    </div>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<div class="new-post">
  <div class="new-post-form">
    <div class="post-form">
      <%= form_with(model: @post, local: true) do |f| %>
      <%= render "devise/shared/error_messages", model: f.object%>
      <div class="post-form">
        <div class="field">
          <%= f.label :image,"Image", class:"post-new-label"%><br />
          <%= f.file_field :image %>
        </div>

        <div class="field">
          <%= f.label :image,"Name", class:"post-new-label" %><br />
          <%= f.text_field :name, placeholder: "Name", class:"post-new-name" %>
        </div>

        <div class="field">
          <%= f.label :image,"Text", class:"post-new-label" %><br />
          <%= f.text_area :text, placeholder: "text", class:"post-new-text" %>
        </div>
      </div>
      <div class="post-send">
        <div class="send-btn">
          <%= f.submit "Update", class:"submit-btn" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="contents">
  <div class="post-side">
    <div class="post-search">
      <div class="search-tag-name">Tagで探す</div>
      <%= form_with(url: search_posts_path, local: true, method: :get, class:"search-form") do |f| %>
        <%= f.text_field :keyword, placeholder: "Tag名を入力する", class:"search-input" %>
        <%= f.submit "検索", class:"search-btn" %>
      <% end %>
      <%= form_with url: search_posts_path, method: :get, class:"search-box", local: true do %>
        <%= select_tag :tag_id,
          options_from_collection_for_select(Tag.all, :id, :tagname, params[:tag_id]),
          {
            prompt: 'タグで絞り込み',
            class: 'select-tag',
            onchange: 'submit(this.form);'
          }%>
      <% end %>
    </div>
  </div>
  <div class="post-main">
    <div class="post-main-body">
      <% @posts.each do |post| %>
        <div class="post">
          <div class="content_post">
            <div class="post-each">
              <div class="post-user-nickname">
                <%= link_to "#{post.user.nickname}", user_path(post.user.id) %>
              </div>
              <% if user_signed_in?%>
                <%= link_to post_path(post.id) do %>
                  <%= image_tag post.image, class:"post-image" %>
                <% end %>
              <% end %>
              <div class="name-likes">
                <div class="name">
                  <%= post.name %>
                </div>
                <div class="likes" id="post_<%= post.id %>">
                  <%= render 'post', post: post %>
                </div>
              </div>
              <p><%= post.text %></p>
              <ul class="tag">
                <li class="tag-list">
                  <% post.tags.each do |tag| %>
                    <%= link_to "##{tag.tagname}", posts_path(params[:tag_id]) %>
                  <% end%>
                </li>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="new-post">
  <div class="new-post-form">
    <div class="post-form">
      <%= form_with(model: @post, url: posts_path, local: true) do |f| %>
      <%= render "devise/shared/error_messages", model: f.object%>
        <div class="post-form">
          <div class="field">
            <%= f.label :image,"Image", class:"post-new-label"%><br />
            <%= f.file_field :image %>
          </div>

          <div class="tag-field", id='tag-field'>
            <%= f.label :tagname, "タグ", class:"tagname-font" %>
            <div class="tag-box">
              <%= f.text_field :tagname, class:"input-tag", id:"posts_tag_tagname" %>
              <%= f.submit "選択", class:"tag-select-btn" %>
            </div>
          </div>
          <div id="search-result">
          </div>

          <div class="field">
            <%= f.label :image,"Name", class:"post-new-label" %><br />
            <%= f.text_field :name, placeholder: "Name", class:"post-new-name" %>
          </div>

          <div class="field">
            <%= f.label :image,"Text", class:"post-new-label" %><br />
            <%= f.text_area :text, placeholder: "text", class:"post-new-text" %>
          </div>
        </div>
        <div class="post-send">
          <div class="send-btn">
            <%= f.submit "SEND", class:"submit-btn" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/search.html.erb
<div class="contents">
  <div class="post-side">
    <div class="post-search">
      <div class="search-tag-name">Tagで探す</div>
      <%= form_with(url: search_posts_path, local: true, method: :get, class:"search-form") do |f| %>
        <%= f.text_field :keyword, placeholder: "Tag名を入力する", class:"search-input" %>
        <%= f.submit "検索", class:"search-btn" %>
      <% end %>
      <%= form_with url: search_posts_path, method: :get, class:"search-box", local: true do %>
        <%= select_tag :tag_id,
          options_from_collection_for_select(Tag.all, :id, :tagname, params[:tag_id]),
          {
            prompt: 'タグで絞り込み',
            class: 'select-tag',
            onchange: 'submit(this.form);'
          }%>
      <% end %>
    </div>
  </div>
  <div class="post-main">
    <div class="post-main-body">
      <% @tags.each do |tag_id|%>
        <% tag_id.posts.each do |post| %>
          <div class="post">
            <div class="content_post">
              <div class="post-each">
                <div class="post-user-nickname">
                  <%= link_to "#{post.user.nickname}", user_path(post.user.id) %>
                </div>
                <%= link_to post_path(post.id) do %>
                  <%= image_tag post.image, class:"post-image" %>
                <% end %>
                <div class="name">
                  <%= post.name %>
                </div>
                <div class="likes" id="post_<%= post.id %>">
                  <%= render 'post', post: post %>
                </div>
                <p><%= post.text %></p>
                <ul class="tag">
                  <li class="tag-list">
                    <% post.tags.each do |tag| %>
                      <%= link_to "##{tag.tagname}", posts_path(params[:tag_id]) %>
                    <% end%>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="post-body">
  <div class="side-ber">
    <div class="post-btn">
      <div class="show-btns">
        <div class="edit-btn">
          <%= link_to 'Edit', edit_post_path %>
        </div>
        <div class="delete-btn">
          <%= link_to 'Delete', post_path(@post.id), method: :delete %>
        </div>
      </div>
    </div>
  </div>
  <div class="post-main">
    <div class="post">
      <div class="content-post">
        <div class="show-post">
          <div class="post-user-nickname">
            <%= link_to "#{@post.user.nickname}", user_path(@post.user.id) %>
          </div>
          <%= image_tag @post.image, class:"post-image" %>
          <div class="name">
            <%= @post.name %>
          </div>
          <div class="likes" id="post_<%= @post.id %>">
            <%= render 'post', post: @post %>
          </div>
          <p><%= @post.text %></p>
          <ul class="tag">
            <li class="tag-list">
              <% @post.tags.each do |tag| %>
                <%= link_to "##{tag.tagname}", posts_path(params[:tag_id]) %>
              <% end%>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="comment-area">
      <div class="container">
        <%= form_with(model: [@post, @comment], local: true) do |f| %>
          <%= f.text_area :comment, placeholder: "コメントする", rows: "2", class:"comment-box" %>
          <%= f.submit "SEND", class:"comment-submit-btn" %>
        <% end %>
        <div class="comment-show">
          <h4>＊コメント一覧＊</h4>
          <% if @comments %>
            <% @comments.each do |comment| %>
              <p>
                <div>
                  <%= link_to comment.user.nickname, "users/#{comment.user_id}" %> :
                  <%= comment.comment %>
                </div>
              </p>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/likes.html.erb
<div class="contents">
  <div class="post-main">
    <div class="post-main-body">
      <% if @like_list.present? %>
        <% @like_list.each do |post| %>
          <div class="post">
            <div class="content_post">
              <div class="post-each">
                <div class="post-user-nickname">
                  <%= link_to "#{post.user.nickname}", user_path(post.user.id) %>
                </div>
                <%= link_to post_path(post.id) do %>
                  <%= image_tag post.image, class:"post-image" %>
                <% end %>
                <div class="name-likes">
                  <div class="name">
                    <%= post.name %>
                  </div>
                  <div class="likes" id="post_<%= post.id %>">
                    <%= render 'posts/post', post: post %>
                  </div>
                </div>
                <p><%= post.text %></p>
                <ul class="tag">
                  <li class="tag-list">
                    <% post.tags.each do |tag| %>
                      <%= link_to "##{tag.tagname}", posts_path(params[:tag_id]) %>
                    <% end%>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-show">
  <div class="side-ber">
    <div class="user-show-nickname">
      <%= @nickname %>
    </div>
    <div class="user-action-btn">
      <div class="user-edit-btn">
        <%= link_to "Edit", edit_user_registration_path(params[:id]) %>
      </div>
      <%= link_to likes_users_path do %>
        <div class="like-btn">
          <%= image_tag "like-icon.jpg", class:"like-icon" %>
          <div class="like-font">いいね</div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="user-main">
    <div class="user-show-info">
      <div class="user-posts">
        <% @posts.each do |post| %>
          <div class="post">
            <div class="content_post">
              <div class="post-each">
                <div class="post-user-nickname">
                  <%= link_to "#{post.user.nickname}", user_path(post.user.id) %>
                </div>
                <%= link_to post_path(post.id) do %>
                  <%= image_tag post.image, class:"post-image" %>
                <% end %>
                <div class="name-likes">
                  <div class="name">
                    <%= post.name %>
                  </div>
                  <div class="likes" id="post_<%= post.id %>">
                    <%= render 'posts/post', post: post %>
                  </div>
                </div>
                <p><%= post.text %></p>
                <ul class="tag">
                  <li class="tag-list">
                    <% post.tags.each do |tag| %>
                      <%= link_to "##{tag.tagname}", posts_path(params[:tag_id]) %>
                    <% end%>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>